---
title: "Descloroclozapine (DCZ) and Angiotensin II (AngII)"
author: "Kevin Shih"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    number_sections: false
    df_print: paged
    code_folding: hide
    highlight: pygments
---

</br>

Deschloroclozapine (DCZ) is a high-affinity, selective, and fast-acting agonist used to target muscarinic DREADDs (Designer Receptors Exclusively Activated by Designer Drugs). DREADDs are modified G-protein coupled receptors (GPCR) that will only activate an intracellular response due to activation by DCZ and can be genetically added into different cell types depending on the desired outcome. For example, Cspg4-Cre;DREADD mice will mainly target pericytes while Pdgfrβ-Cre;DREADD will target fibroblasts, vascular smooth muscle cells, and pericytes. Note that both of these mice need to be Tamoxifen injected in order to activate the genes coding for the DREADD receptors.

</br>

# Materials

</br>

1. Descholoclozapine from HelloBio. (SKU HB9126-5mg)
2. Sterile Invitrogen Ultradistilled Water (3138564)
3. Angiotensin II (_______)
4. 11x 1.5mL Eppendorf Tubes


# Nelson Lab Calculations

</br>

The DCZ will be in powder form when received. Store at -20°C.

</br>

1. Add 1mL of DI water directly to the tube with the DCZ powder. Cap, shake well, and vortex for 10 seconds to fully homogenize the solution.
2. Aliquot the DCZ solution into 5x 1mL Eppendorf tubes (label with drug, concentration, date, name)
3. Label 5 other tubes with the following names
  - 1:20
  - 100 ug/kg
  - 10 ug/kg
  - 5 ug/kg
  - 1 ug/kg
4. From the aliquot (5mg/mL) (vortex), take 50uL of the solution and add to 950uL of DI water in the 1:20 Eppendorf tube
5. From the 1:20 Eppendorf tube (vortex first), take 100uL and add to 900uL of DI water in the 100 ug/kg Eppendorf tube
6. From the 100 ug/kg tube (vortex first), take 100uL and add to 900uL of DI water in the 10ug/kg Eppendorf tube
7. From the 100 ug/kg tube (vortex first), take 50uL and add to 950uL of DI water in the 5ug/kg Eppendorf tube
8. From the 100 ug/kg tube (vortex first), take 10uL and add to 990uL of DI water in the 1ug/kg Eppendorf tube

</br>

# Angiotensin II Calculations

1. Add 20uL to 1mL DI water (360ug/kg)












</br>
This page was last edited on August 11, 2026 by Kevin Shih
