---
title: "Evans Blue Dye Protocol"
author: "Kevin Shih"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    number_sections: false
    df_print: paged
    code_folding: hide
    highlight: pygments
---

Desired concentration of Evans Blue Dye: 10mg/mL

# Materials

  - ThermoScientific Evans Blue Dye (5g)
  - Sterile DPBS Saline
  - Eppendorf Tubes

</br>

# Purpose

Injection via tail vein injection on mice.  Note: according to JWN, if only used to test on mice and not as part of an experiment, the mice will be sac’d shortly after injection and thus sterile saline does not need to be used.

Amount to be injected: 50uL of 10mg/mL solution per 10g of bodyweight (20g mouse = 100uL)

</br>

# Pre-Label Tubes

  - Determine the total number of tubes you will be making aliquots of (Ex: 10 tubes for 0.1g EB, 50 tubes for 0.5g EB)
  - Label tubes with date/name/concentration and whether sterile or unsterile saline was used

</br>

# Steps to make 10 1mL aliquots at a concentration of 10mg/mL

  - Weigh out 0.1g of Evans Blue Dye
  - Put into a 15mL conical tube
  - Bring the volume up to 10mL using saline
  - Vortex the solution for 5 seconds
  - Aliquot 1mL of the solution into 10x 1.5mL Eppendorf Tubes

</br>

# Storage

Short Term (1 month) 

  - Store at 4ºC in a sealed, dark, light-proof container

Long Term (up to 6 months)

  - -20ºC or -80ºC

</br>

This page was edited on 8/28/2026 by Kevin Shih.