---
title: "Nuclei Isolation Protocol"
author: "Kevin Shih"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    number_sections: false
    df_print: paged
    code_folding: hide
    highlight: pygments

---


<style>
table {
  margin-left: auto;
  margin-right: auto;
}

th, td {
  text-align: center;
}
</style>

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}

th, td {
  padding: 6px;
}
</style>  



# Nuclei Isolation Protocol Materials

- 10X Genomics Chromium Nuclei Isolation Kit
- Tissue scissors
- Beaker for liquid waste
- 0.4% Trypan Blue


<br>

This protocol was derived from the [Xenium 10X Nuclei Isolation Protocol]()

## Lysis Buffer
 
  | Reagent | 1 Reaction | 2 Reactions | 3 Reactions | 4 Reactions |
|---|---|---|---|---|
| Lysis Reagent | 536uL | 1mL 72uL | 1mL 608uL | 2mL 144uL |
| Reducing Agent B | 0.5uL | 1uL | 1.5uL | 2uL |
| Surfactant A | 5.5uL | 11uL | 16.5uL | 22uL |
| RNase Inhibitor | 13.9uL | 27.8uL | 41.7uL | 55.6uL |
  
Note: Lysis Reagent and Surfactant A are found in the 4°C.  
Note: Reducing Agent B and RNase Inhibitor are found in the -20°C.

<br>

## Debris Removal Buffer
  
   | Reagent | 1 Reaction | 2 Reactions | 3 Reactions | 4 Reactions |
|---|---|---|---|---|
| Debris Removal | 550uL | 1mL 100uL | 1mL 650uL | 2mL 200uL |
| Reducing Agent B | 0.5uL | 1uL | 1.5uL | 2uL |

Note: Debris Removal Reagent is found in the 4°C.  
Note: Reducing Agent B is found in the -20°C.

<br>

## Wash and Resuspension Buffer
  | Reagent | 1 Reaction | 2 Reactions | 3 Reactions | 4 Reactions |
|---|---|---|---|---|
| 1X PBS | 2mL 887.5uL | 5mL 775uL | 8mL 662.5uL | 11mL 550uL |
| 10% BSA | 330uL | 660uL | 990uL | 1mL 320uL |
| RNase Inhibitor | 82.5uL | 165uL | 247.5uL | 330uL |

Note: 1X PBS is found in Bench 3 cabinet.  
Note: 10% BSA is found in the 4°C.

<br>

# Step-by-Step Protocol

## Experimental Setup

1. Obtain ice (make sure to keep all samples and reagents on ice)
2. Prepare and label the reagents in 15mL conical tubes and keep on ice.
3. Label 2 round bottom-tubes from the 10X Consumables Box and 1 pointed-bottom tubes and keep on ice.
4. Obtain the tube with the half-kidney from the -80°C freezer.
5. Turn on the centrifuge and set to 4°C for fast temperature control

<br>

## Experiment

6. Transfer the sample from the tube in the -80°C to the new pointed-bottom tube that was obtained from the Consumables Box.
7. Add 200uL of the Lysis Buffer to the sample
8. Using surgical scissors, mince the 1/2 kidney as much as possible to prevent large chunks of tissue being present
9. Using the green pestle, *GENTLY* push down against the tissue for a maximum of 10x
10. Add 300uL of Lysis Buffer and incubate for <u>10 minutes</u> on ice  
  10a. During this time, set up your centrifuge to 16,000 rcf (also may show up as 16,000 g; rcf=g), for 20 seconds, at 4°C.  
  10b. Set up the Collection Tube (round-bottom) with the Nuclei Isolation Column in it on ice during the lysis so the tube can cool
11. Transfer the dissociated tissue onto the column and close the top of the Nuclei Isolation Column
12. Put the tube into the centrifuge and spin at the preset settings (16,000rcf, 20s, 4°C) (make sure to balance centrifuge)
13. Once the centrifuge is done, discard the column (pellet should be visible at the bottom/side of the tube). 
14. If tube is fully intact, cap the tube and vortex for 10 seconds to resuspend the nuclei. If cap is not intact see 14a  
  14a. If the cap has broken off during the centrifuge step (step 12), resuspend your nuclei by pipetting gently up and down for a maximum of 10x (you should see a curtain effect where the cells lift off the edge of the cap and float initially). Make sure to fully resuspend the cells so no clumps are present
15. Set your centrifuge to 500 rcf (g), for 3 minutes, at 4°C and spin your sample down (make sure to balance centrifuge and put the spine of the cap facing outwards)
16. Gently remove your sample from the centrifuge and close the centrifuge to keep it cold
17. Carefully pipette your supernatant (excess fluid) into a waste container (your pellet should be visible so it will be easier to see and should be on the side of the tube's spine)
18. Resuspend the pellet in 500uL of Debris Removal Buffer and place on ice
19. Change the settings on the centrifuge to 700rcf, for 10 minutes, at 4°C and spin your sample (balance the centrifuge)
20. Carefully remove the sample from the centrifuge (note that your pellet will have seemingly disappeared)
21. Carefully remove as much of the Debris Removal Buffer as possible without disturbing the pellet (if the pellet starts to move then do NOT continue removing buffer)
22. Resuspend the nuclei with 1mL of Resuspension Buffer (can pipette up and down for a maximum of 10x)
23. Set the centrifuge to 500rcf, for 5 min, at 4°C and spin down cells (balance the centrifuge)
24. Remove your sample from the centrifuge carefully (pellet should be visible), and remove the supernatant
25. Resuspend the nuclei with 1mL of Resuspension Buffer (can pipette up and down for a maximum of 10x)
26. Spin sample again at  500rcf, for 5 min, at 4°C (balance the centrifuge)
27. Remove your sample from the centrifuge carefully (pellet should be visible), and remove the supernatant
28. Resuspend your pellet in 20-500uL of Wash and Resuspension Buffer
29. Vortex for 3 seconds

<br>

## Visualization

### Protocol


30. Obtain a 0.6mL Eppendorf Tube
31. Add 10uL of 0.4% Trypan Blue to the bottom of the tube
32. Add 10uL of Sample into the bottom of the tube and gently pipette up and down a few times to mix
33. Incubate <u>on ice</u> for a minimum of 2 minutes
34. Pipette 10uL of the dyed sample onto a hemocytometer (with the cover slip on top) and allow for capillary action to move the sample evenly

<br>

### Light Microscopy

Note: Located in the 2nd lab

35. Place slide on stage of Leica DMIL LED light microscope
36. Turn on the light (right side of the microscope)

<br>

### Epifluorescence Microscopy

Note: Located in the microscope room

37. Log in to the computer
38. Open the LASX program, wait for it to load, and click "Ok"
39. To the left of the microscope, turn the switch on for the CiR Advanced
40. To the box to the left of the CiR Advanced, turn on the switch
41. Turn on the shutter on the main screen and click on the objective with the eye to allow light to reach the eye piece
42. Once nuclei are in focus, on the computer click the "Live" button on the lower left part of the screen
43. Adjust Gain and Exposure levels in the upper left part of the LASX software
44. To take the picture, click on "Single Image" which will take the picture and immediately turn off Live imaging
45. Under projects, save the picture/folder
  45a. For individual pictures, right click and export to either .png, .tif, .jpeg
46. To turn off the machine, close the LASX software completely
47. Turn off the light box to the left of the CiR Advanced
48. Turn off CiR Advanced
49. Remove your slide
50. Clean station, log out of computer, and close door


<br>

This protocol was last amended on July 17th, 2026 by Kevin Shih

<br>









