<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>ROC 1</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Learning Bioinformatics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    About
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="about.html">About</a>
    </li>
    <li>
      <a href="contributors.html">Contributors</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Getting Started
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="computer_requirements.html">Computer Requirements</a>
    </li>
    <li>
      <a href="downloading_R.html">Downloading R</a>
    </li>
    <li>
      <a href="using_packages.html">Using Packages</a>
    </li>
    <li>
      <a href="best_practices.html">Jonathan's Best Coding Practices</a>
    </li>
    <li>
      <a href="rules_of_coding.html">Jonathan's Rule of Coding</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Github Tutorials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="qupath_install.html">Understanding Github</a>
    </li>
    <li>
      <a href="github_tutorial.html">Github Tutorial</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    snRNAseq Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="roc_1.html">ROC 1</a>
    </li>
    <li>
      <a href="write_degs_excel.html">Write DEGs to Excel</a>
    </li>
    <li>
      <a href="coding_crumbs.html">SCORE: Coding Crumbs</a>
    </li>
    <li>
      <a href="recreating_figures.html">SCORE: Recreating Figures</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    QuPath Tutorials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="qupath_install.html">Installing QuPath</a>
    </li>
    <li>
      <a href="qupath_manual_annotation.html">Manual Cell Annotation</a>
    </li>
    <li>
      <a href="qupath_composite_classifications.html">Creating Composite Classifications</a>
    </li>
    <li>
      <a href="qupath_analyze_in_r.html">Analyzing QuPath data in R</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Problem Solving
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="write_degs_excel.html">Write DEGs to Excel</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">ROC 1</h1>

</div>


<p><strong>Tutorial written by Jonathan Nelson</strong></p>
<p><strong>Tutorial adapted by Sienna Blanche</strong></p>
<div id="getting-started" class="section level1">
<h1>Getting Started</h1>
<p>For our first scRNA-seq analysis, we’ll be following a clear,
step-by-step process divided into nine parts.</p>
</div>
<div id="necessary-materials" class="section level1">
<h1>Necessary materials</h1>
<p>The dataset that we are using is from Karaiskos et al. JASN 2018
(PMID: 29794128). This is 1 of 3 files (glom_rep3) downloaded from its
corresponding GEO entry (<a
href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE111107"
class="uri">https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE111107</a>.
This dataset was chosen because it is a relatively small number of cells
and a limited number of clusters to simplify calculations and
analysis.</p>
</div>
<div id="step-0-installing-the-seurat-and-dependency-packages."
class="section level1">
<h1>Step 0: Installing the Seurat (and dependency packages).</h1>
<p>You only need to perform Step 0 once. Copy the command
<strong>install.packages(‘Seurat’)</strong> into your R script or RMD
and run it. Confirm that the package has been downloaded.</p>
</div>
<div id="step-1-activate-the-r-packages-needed-to-run-the-analysis."
class="section level1">
<h1>Step 1: Activate the R packages needed to run the analysis.</h1>
<p>Copy the following lines of code into your file and run them:</p>
<p><strong>library(Seurat)</strong></p>
<p><strong>library(cowplot)</strong></p>
<p><strong>library(dplyr)</strong></p>
<p><strong>library(patchwork)</strong></p>
</div>
<div
id="step-2-setting-up-a-working-directory-and-uploading-the-scrnaseq-file-to-r-studio"
class="section level1">
<h1>Step 2: Setting up a “Working Directory” and uploading the scRNAseq
file to R studio</h1>
<p>First we need to tell R studio where our scRNAseq “.csv” file is.
Click on Session&gt;Set Working Directory&gt;Choose Directory and find
the folder on your computer that contains the downloaded dataset.</p>
<p><img
src="Images/ROC_1_Screenshot%201.png" /></p>
<p>Once you’ve set your working directory copy and run the following
code: <strong>Glom = read.csv(‘Glom_scRNAseq.csv’,row.names=1)</strong>.
If you have pointed to the right folder then the Environment window
should contain a data object called “Glom” after a few seconds</p>
<p><img
src="Images/ROC_1_Screenshot%202.png" /></p>
</div>
<div
id="step-3-transforming-scrnaseq-.csv-file-into-a-matrix-and-loading-it-into-seurat"
class="section level1">
<h1>Step 3: Transforming scRNAseq “.csv” file into a matrix and loading
it into Seurat</h1>
<p>We will next convert the “.csv” file into a data matrix that is able
to be uploaded into Seurat. Copy and run the following code:
<strong>Glom = data.matrix(Glom)</strong>. The object in the Environment
window will change to be a “Large Matrix”</p>
<p><img
src="Images/ROC_1_Screenshot%203.png" /></p>
<p>Next we will run a “Sanity check” to make sure our Matrix file is
formatted correctly. Run the following code
<strong>Glom[1:5,1:5]</strong> to see the first 5 rows and columns of
the matrix in the console window. Top row should be bar codes and first
column should be gene names, as seen below.</p>
<pre><code>##                CTCTTTATGGCT TCCTATGTGTCN CTACCCCTCAAA AACCCTCTATGT TTATTGCCCTTC
## 00R_AC107638.2            0            0            0            0            0
## 0610005C13Rik             0            0            0            0            0
## 0610007P14Rik             0            2            0            3            0
## 0610009B22Rik             0            0            2            0            0
## 0610009E02Rik             0            0            0            0            0</code></pre>
<p>Next we will load this data into Seurat and create our Seurat Object.
Run the following code:</p>
<p><strong>Glom &lt;- CreateSeuratObject(counts = Glom, project =
“ROC_Glom”, min.cells = 3, min.features = 200)</strong></p>
<p>The object in the Environment window will change to be a “Large
Seurat”</p>
<p><img
src="Images/ROC_1_Screenshot%204.png" /></p>
<p>This is our first filtering step. The code selects only genes that
are expressed in at least 3 cells and cells that express at least 200
genes. Next we will run another sanity check to see how many cells and
genes were filtered by running the following code
<strong>Glom</strong>.</p>
<pre><code>## An object of class Seurat 
## 16991 features across 3035 samples within 1 assay 
## Active assay: RNA (16991 features, 0 variable features)
##  1 layer present: counts</code></pre>
<p>You should now get an output with 3035 Samples (cells) by 16991
Features (genes) which means we filtered out 42 cells and 5319 Genes! We
know this by comparing out new object to the object we first loaded into
the session.</p>
</div>
<div id="step-4-visualizing-quality-control-metrics"
class="section level1">
<h1>Step 4: Visualizing Quality Control Metrics</h1>
<p>Run the following code <strong>Glom[[“percent.mt”]] &lt;-
PercentageFeatureSet(Glom, pattern = “^mt-”)</strong> to create a new
meta.data feature in the Seurat object that measures how much
mitochondrial DNA there is in each cell.</p>
<p>We will now visualize the dataset for quality control using 3
different metrics by running the following line of code:
<strong>VlnPlot(Glom, features = c(“nFeature_RNA”, “nCount_RNA”,
“percent.mt”), ncol = 3)</strong></p>
<p>nFeature_RNA is the number of differing genes detected in each cell,
nCount_RNA refers to the number of mRNA molecules detected in each cell,
and percent.mt is the percent of counts that come from mitochondrial
genes.</p>
<p>The graph you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Now we will interpret this information to filter out doublets and
damaged cells by running the following code: <strong>Glom &lt;-
subset(Glom, subset = nFeature_RNA &lt; 2000 &amp; nCount_RNA &lt; 4000
&amp; percent.mt &lt; 20)</strong></p>
<p>High nFeature_RNA or nCount_RNA could equate to doublets or mixed
cell debris. We will filter out cells with more than 2000 genes and 4000
mRNA molecules to exclude potential doublets or mixed cell debris. High
percent.mt could equate to damaged cells. We will filter out cells with
more than 20% mitochondrial content to exclude damaged cells.</p>
<p>Now we will replot the graphs to visualize the plots again with the
newly filtered data by running <strong>VlnPlot(Glom, features =
c(“nFeature_RNA”, “nCount_RNA”, “percent.mt”), ncol = 3)</strong></p>
<p>The new graph should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Next we will run another sanity check to see how many cells and genes
were filtered from the previous command by running
<strong>Glom</strong>.</p>
<pre><code>## An object of class Seurat 
## 16991 features across 2883 samples within 1 assay 
## Active assay: RNA (16991 features, 0 variable features)
##  1 layer present: counts</code></pre>
<p>The output we get is as follows: 2899 Samples (cells) by 16991
Features (genes). This means we filtered out 136 cells and 0 Genes!
Again we know this by comparing the current object to the one we had in
previous steps.</p>
</div>
<div
id="step-5-data-normalization-and-identification-of-genes-driving-variability-cluster-formation"
class="section level1">
<h1>Step 5: Data Normalization and Identification of Genes Driving
Variability (cluster formation)</h1>
<p>Run the following code</p>
<p><strong>Glom &lt;- NormalizeData(Glom, normalization.method =
“LogNormalize”, scale.factor = 10000)</strong></p>
<p><strong>Glom &lt;- NormalizeData(Glom)</strong></p>
<p><strong>Glom &lt;- FindVariableFeatures(Glom, selection.method =
“vst”, nfeatures = 2000)</strong></p>
<p>This normalizes the matrix and creates a plot of the genes that are
the most variable in the dataset.</p>
<p>Next we can identify the 10 most highly variable genes by creating a
new object in the environment called “top10”. To do this copy the
following code: <strong>top10 &lt;- head(VariableFeatures(Glom),
10)</strong>.</p>
<p>The top 10 genes I got were as follows:</p>
<pre><code>##  [1] &quot;S100g&quot;   &quot;Fxyd2&quot;   &quot;Klk1&quot;    &quot;Atp1b1&quot;  &quot;Defb1&quot;   &quot;Pvalb&quot;   &quot;Spp1&quot;   
##  [8] &quot;Umod&quot;    &quot;Wfdc15b&quot; &quot;Slc12a3&quot;</code></pre>
<p>Next we can create a plot of the variable features within the dataset
and label the top 10 genes to see which are driving the clustering. To
do so copy the following code:</p>
<p><strong>plot1 &lt;- VariableFeaturePlot(Glom)</strong></p>
<p><strong>plot2 &lt;- LabelPoints(plot = plot1, points = top10, repel =
TRUE)</strong></p>
<p><strong>plot2</strong></p>
<p>The graph you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="step-6-creation-and-visualization-of-principal-components"
class="section level1">
<h1>Step 6: Creation and Visualization of Principal Components</h1>
<p>Run the following code:</p>
<p><strong>all.genes &lt;- rownames(Glom)</strong></p>
<p><strong>Glom &lt;- ScaleData(Glom, features = all.genes)</strong></p>
<p><strong>Glom &lt;- RunPCA(Glom, features = VariableFeatures(object =
Glom))</strong></p>
<p><strong>print(Glom[[“pca”]], dims = 1:10, nfeatures = 3)</strong></p>
<p>This calculates the principal components and then prints the 5 genes
that drive the first 5 principal components.</p>
<pre><code>## PC_ 1 
## Positive:  Cdkn1c, Nupr1, Anxa1 
## Negative:  Atp1b1, Defb1, Ldhb 
## PC_ 2 
## Positive:  Srgn, Ly6c1, Emcn 
## Negative:  Sdc4, Cdkn1c, Fos 
## PC_ 3 
## Positive:  Ly6c1, Srgn, Egfl7 
## Negative:  Acta2, Tpm2, Myl9 
## PC_ 4 
## Positive:  Hsd11b2, Aqp3, Aqp2 
## Negative:  Pvalb, Ppp1r1a, Umod 
## PC_ 5 
## Positive:  Gm23935, Lars2, Gm15564 
## Negative:  Atf3, Nfkbia, Btg2 
## PC_ 6 
## Positive:  Igfbp5, Ehd3, Kdr 
## Negative:  S100a4, Tspan8, Cd93 
## PC_ 7 
## Positive:  Calb1, Kl, Hsd11b2 
## Negative:  Atp6v1g3, Tyrobp, Cytip 
## PC_ 8 
## Positive:  Tyrobp, Fcer1g, Cytip 
## Negative:  Atp6v1g3, Car2, Slc4a9 
## PC_ 9 
## Positive:  Atf3, Ifrd1, Zfp36 
## Negative:  Gm23935, Lars2, Col4a3 
## PC_ 10 
## Positive:  Klk1, Klk1b5, Plac8 
## Negative:  Gstm2, Lsp1, Cxcl1</code></pre>
<p>Can you get a sense for how the cells might be clustering based off
of these genes?</p>
<p>Now we will visualize the genes driving the PCA a few ways. Run the
next lines code individually.</p>
<p>This line visualizes the genes driving the first 2 PCA
dimensions:</p>
<p><strong>VizDimLoadings(Glom, dims = 1:2, reduction =
“pca”)</strong></p>
<p>The graph you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Next, this line visualizes the scRNAseq dataset as a PCA (hopefully
you can appreciate the poor clustering):</p>
<p><strong>DimPlot(Glom, reduction = “pca”)</strong></p>
<p>The graph you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Lastly, this line creates a heatmap of the top 500 genes that drive
the first 2 PCA dimensions:</p>
<p><strong>DimHeatmap(Glom, dims = 10:11, cells = 500, balanced =
TRUE)</strong></p>
<p>The heatmap you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>This plot shows the variability and helps to decide how many PCA
dimensions to use when measuring the clusters. When the standard
deviation in the PC dimensions becomes small it no longer has a big
effect. In this case we will use 10 PC’s.</p>
<p><strong>ElbowPlot(Glom)</strong></p>
<p>The elbowplot you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
</div>
<div id="step-7-calculation-and-creation-of-a-umap-visualization"
class="section level1">
<h1>Step 7: Calculation and Creation of a UMAP visualization</h1>
<p>This is where scRNAseq becomes more like like and art form. The
following lines determine the shape of the clusters and the number of
populations in our scRNASeq visualization.</p>
<p>These lines control the resolution of the clusters and the number of
separate populations. <em>FindNeighbors</em> changes the separation
between clusters. <em>FindClusters</em> changes the number of
differential populations.</p>
<p><strong>Glom &lt;- FindNeighbors(Glom, dims = 1:10)</strong></p>
<p><strong>Glom &lt;- FindClusters(Glom, resolution = 0.1)</strong></p>
<p><strong>Glom &lt;- RunUMAP(Glom, dims = 1:10)</strong></p>
<pre><code>## Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck
## 
## Number of nodes: 2883
## Number of edges: 100922
## 
## Running Louvain algorithm...
## Maximum modularity in 10 random starts: 0.9463
## Number of communities: 4
## Elapsed time: 0 seconds</code></pre>
<p>This line generates the UMAP visualization. How many clusters do you
see? Do they seem like they are real clusters?</p>
<p><strong>DimPlot(Glom, reduction = “umap”)</strong></p>
<p>The plot you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>This line generates the UMAP visualization. How many clusters do you
see? Do they seem like they are real clusters?</p>
<p><strong>Glom2 &lt;- FindClusters(Glom, resolution = 0.3)</strong></p>
<p><strong>Glom2 &lt;- RunUMAP(Glom2, dims = 1:10)</strong></p>
<p><strong>DimPlot(Glom2, reduction = “umap”)</strong></p>
<pre><code>## Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck
## 
## Number of nodes: 2883
## Number of edges: 100922
## 
## Running Louvain algorithm...
## Maximum modularity in 10 random starts: 0.8870
## Number of communities: 8
## Elapsed time: 0 seconds</code></pre>
<p>The dimplot you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div
id="step-8-generation-of-heatmaps-of-differential-genes-between-clusters-to-identify-cell-types"
class="section level1">
<h1>Step 8: Generation of Heatmaps of differential genes between
clusters to identify cell types</h1>
<p>Now that we have a UMAP we have to identify the cell type that each
cluster represents. We will do this by finding the top 5 genes that
define each cluster and making a heatmap. Notice if there are any clues
to what each cluster is based on the genes enriched in the
population.</p>
<p>Run the following code:</p>
<p><strong>Glom.markers &lt;- FindAllMarkers(Glom, only.pos = TRUE,
min.pct = 0.25, logfc.threshold = 0.25)</strong></p>
<p><strong>Glom.markers %&gt;% group_by(cluster) %&gt;% top_n(n = 5, wt
= avg_log2FC)</strong></p>
<p><strong>top5 &lt;- Glom.markers %&gt;% group_by(cluster) %&gt;%
top_n(5, avg_log2FC)</strong></p>
<p><strong>DoHeatmap(Glom, features = top5$gene)</strong></p>
<pre><code>## # A tibble: 20 × 7
## # Groups:   cluster [4]
##        p_val avg_log2FC pct.1 pct.2 p_val_adj cluster gene    
##        &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;   &lt;chr&gt;   
##  1 4.64e-212       3.96 0.733 0.074 7.88e-208 0       Clic3   
##  2 2.53e-118       4.18 0.49  0.041 4.30e-114 0       Tcf21   
##  3 4.46e- 63       4.08 0.304 0.026 7.58e- 59 0       Fgfbp1  
##  4 8.60e- 59       3.90 0.283 0.023 1.46e- 54 0       Hs3st6  
##  5 1.21e- 56       4.43 0.271 0.021 2.06e- 52 0       Zbtb8a  
##  6 0               7.04 0.672 0.015 0         1       Srgn    
##  7 0               6.84 0.633 0.022 0         1       Ly6c1   
##  8 4.98e-307       6.99 0.593 0.011 8.46e-303 1       Emcn    
##  9 1.01e-284       6.95 0.563 0.013 1.72e-280 1       Egfl7   
## 10 2.40e-203       6.62 0.43  0.013 4.08e-199 1       Ctla2a  
## 11 0               9.17 0.53  0.001 0         2       Epcam   
## 12 3.12e-299       9.42 0.515 0.001 5.30e-295 2       Pgam2   
## 13 4.25e-195      12.8  0.318 0     7.22e-191 2       Cdkl1   
## 14 3.78e-153      10.7  0.258 0     6.41e-149 2       Krt8    
## 15 4.91e-144      10.1  0.25  0.001 8.34e-140 2       Krt18   
## 16 5.68e-256       9.20 0.562 0.006 9.64e-252 3       Acta2   
## 17 6.09e-228       9.53 0.427 0.002 1.03e-223 3       Myh11   
## 18 1.93e-209      10.7  0.36  0.001 3.28e-205 3       Map3k7cl
## 19 5.96e-203       8.94 0.36  0.001 1.01e-198 3       Akr1b7  
## 20 1.06e-160       8.91 0.281 0.001 1.80e-156 3       Fxyd1</code></pre>
<p>The heatmap you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>We will double check our work by visualizing some “traditional”
cell-type markers with violin plots. The markers used in this tutorial
are as follows:</p>
<p>Nphs2 = Podocyte</p>
<p>Pecam1 = Endothelial</p>
<p>Slc12a3 = Tubule</p>
<p>Tagln = Mural</p>
<p>Run the following code to visulaize the markers in each cluster:
<strong>VlnPlot(Glom, features = c(“Nphs2”, “Pecam1”, “Slc12a3”,
“Tagln”))</strong></p>
<p>The graph you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
</div>
<div id="step-9-re-naming-clusters-by-cell-type" class="section level1">
<h1>Step 9: Re-naming clusters by cell-type</h1>
<p>Now that we think that We know the cluster identifiers, we will
insert that meta.data into the Seurat object by running the following
code:</p>
<p><strong>new.cluster.ids &lt;- c(“Podo”, “Endo”, “Tubule”,
“Mural”)</strong></p>
<p><strong>names(new.cluster.ids) &lt;- levels(Glom)</strong></p>
<p><strong>Glom &lt;- RenameIdents(Glom, new.cluster.ids)</strong></p>
<p><strong>DimPlot(Glom, reduction = “umap”, label = TRUE, pt.size =
0.5, label.size = 7, repel = FALSE)</strong></p>
<p>The dimplot you get should now look like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>These labels will now follow each cluster on any visualization we do.
See how they look on the violin plot we ran before by running the
following code:</p>
<p><strong>VlnPlot(Glom, features = c(“Nphs2”, “Pecam1”, “Slc12a3”,
“Tagln”))</strong></p>
<p>The graph you get should now look like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Next we can visualize the expression of each gene on the UMAP diagram
by running the following lines individually.</p>
<p><strong>FeaturePlot(Glom, features = c(“Nphs2”),label = TRUE, pt.size
= 0.5, label.size = 7, repel = FALSE)</strong></p>
<p><strong>FeaturePlot(Glom, features = c(“Pecam1”),label = TRUE,
pt.size = 0.5, label.size = 7, repel = FALSE)</strong></p>
<p><strong>FeaturePlot(Glom, features = c(“Slc12a3”),label = TRUE,
pt.size = 0.5, label.size = 7, repel = FALSE)</strong></p>
<p><strong>FeaturePlot(Glom, features = c(“Tagln”),label = FALSE,
pt.size = 0.5, label.size = 7, repel = FALSE)</strong></p>
<p>The series of feature plots you get should look something like
this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-29-1.png" width="672" /><img src="roc_1_files/figure-html/unnamed-chunk-29-2.png" width="672" /><img src="roc_1_files/figure-html/unnamed-chunk-29-3.png" width="672" /><img src="roc_1_files/figure-html/unnamed-chunk-29-4.png" width="672" /></p>
<p>Using the following code we can highlight a “hidden cluster” that is
probably immune cells because of the unique expression of Ptprc
(CD45):</p>
<p><strong>FeaturePlot(Glom, features = c(“Ptprc”),label = TRUE, pt.size
= 0.5, label.size = 7, repel = FALSE)</strong></p>
<p>The feature plot you get should look something like this:</p>
<p><img src="roc_1_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
</div>
<div id="session-info" class="section level1">
<h1>Session Info</h1>
<pre class="r"><code>sessionInfo()</code></pre>
<pre><code>## R version 4.4.2 (2024-10-31)
## Platform: aarch64-apple-darwin20
## Running under: macOS Sequoia 15.1
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib 
## LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## time zone: America/Los_Angeles
## tzcode source: internal
## 
## attached base packages:
## [1] grid      stats     graphics  grDevices utils     datasets  methods  
## [8] base     
## 
## other attached packages:
##  [1] viridis_0.6.5      viridisLite_0.4.2  gplots_3.2.0       reshape2_1.4.4    
##  [5] pheatmap_1.0.12    ggvenn_0.1.10      lubridate_1.9.4    forcats_1.0.0     
##  [9] stringr_1.5.1      purrr_1.0.2        readr_2.1.5        tidyr_1.3.1       
## [13] tibble_3.2.1       tidyverse_2.0.0    devtools_2.4.5     usethis_3.1.0     
## [17] here_1.0.1         ggpmisc_0.6.1      ggpp_0.5.8-1       ggplot2_3.5.1     
## [21] knitr_1.49         patchwork_1.3.0    Seurat_5.2.1       SeuratObject_5.0.2
## [25] sp_2.1-4           dplyr_1.1.4       
## 
## loaded via a namespace (and not attached):
##   [1] RColorBrewer_1.1-3     rstudioapi_0.17.1      jsonlite_1.8.9        
##   [4] magrittr_2.0.3         spatstat.utils_3.1-2   farver_2.1.2          
##   [7] rmarkdown_2.29         fs_1.6.5               vctrs_0.6.5           
##  [10] ROCR_1.0-11            memoise_2.0.1          spatstat.explore_3.3-4
##  [13] htmltools_0.5.8.1      polynom_1.4-1          sass_0.4.9            
##  [16] sctransform_0.4.1      parallelly_1.41.0      KernSmooth_2.23-24    
##  [19] bslib_0.8.0            htmlwidgets_1.6.4      ica_1.0-3             
##  [22] plyr_1.8.9             plotly_4.10.4          zoo_1.8-12            
##  [25] cachem_1.1.0           igraph_2.1.4           mime_0.12             
##  [28] lifecycle_1.0.4        pkgconfig_2.0.3        Matrix_1.7-1          
##  [31] R6_2.5.1               fastmap_1.2.0          fitdistrplus_1.2-2    
##  [34] future_1.34.0          shiny_1.10.0           digest_0.6.37         
##  [37] colorspace_2.1-1       rprojroot_2.0.4        tensor_1.5            
##  [40] RSpectra_0.16-2        irlba_2.3.5.1          pkgload_1.4.0         
##  [43] labeling_0.4.3         progressr_0.15.1       timechange_0.3.0      
##  [46] spatstat.sparse_3.1-0  httr_1.4.7             polyclip_1.10-7       
##  [49] abind_1.4-8            compiler_4.4.2         remotes_2.5.0         
##  [52] withr_3.0.2            fastDummies_1.7.5      pkgbuild_1.4.6        
##  [55] MASS_7.3-61            quantreg_5.99.1        sessioninfo_1.2.2     
##  [58] caTools_1.18.3         gtools_3.9.5           tools_4.4.2           
##  [61] lmtest_0.9-40          httpuv_1.6.15          future.apply_1.11.3   
##  [64] goftest_1.2-3          glue_1.8.0             nlme_3.1-166          
##  [67] promises_1.3.2         Rtsne_0.17             cluster_2.1.6         
##  [70] generics_0.1.3         gtable_0.3.6           spatstat.data_3.1-4   
##  [73] tzdb_0.4.0             hms_1.1.3              data.table_1.16.4     
##  [76] utf8_1.2.4             spatstat.geom_3.3-5    RcppAnnoy_0.0.22      
##  [79] ggrepel_0.9.6          RANN_2.6.2             pillar_1.10.1         
##  [82] spam_2.11-1            RcppHNSW_0.6.0         later_1.4.1           
##  [85] splines_4.4.2          lattice_0.22-6         survival_3.7-0        
##  [88] deldir_2.0-4           SparseM_1.84-2         tidyselect_1.2.1      
##  [91] miniUI_0.1.1.1         pbapply_1.7-2          gridExtra_2.3         
##  [94] scattermore_1.2        xfun_0.50              matrixStats_1.5.0     
##  [97] stringi_1.8.4          lazyeval_0.2.2         yaml_2.3.10           
## [100] evaluate_1.0.3         codetools_0.2-20       cli_3.6.3             
## [103] uwot_0.2.2             xtable_1.8-4           reticulate_1.40.0     
## [106] munsell_0.5.1          jquerylib_0.1.4        Rcpp_1.0.14           
## [109] globals_0.16.3         spatstat.random_3.3-2  png_0.1-8             
## [112] spatstat.univar_3.1-1  parallel_4.4.2         MatrixModels_0.5-3    
## [115] ellipsis_0.3.2         dotCall64_1.2          profvis_0.4.0         
## [118] urlchecker_1.0.1       bitops_1.0-9           listenv_0.9.1         
## [121] scales_1.3.0           ggridges_0.5.6         rlang_1.1.5           
## [124] cowplot_1.1.3</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
